### ISSUE TITLE
Improve the plain ascii output 

### ISSUE THREAD

**Issue by parro-it** [SamVerschueren/listr#52]
I really like that `listr` produce by default useful output when redirected to file:

```
[05:30:10] Upgrading last deals [started]
[05:30:13] Upgrading last deals [completed]
[05:30:13] Find unsaved measures [started]
[05:30:35] Find unsaved measures [completed]
[05:30:35] Saving measures [started]
[05:30:35] Saving measures [completed]
[05:30:35] All measures saved [started]
[05:30:35] All measures saved [completed]
```

But since I append it to a log file, I would need at least the date to appear before the hour. If we could customize the format with an option or something it would be beautiful...

**Comment by SamVerschueren** [comment]
Yes that would be nice. It should be added as an option to the [verbose-renderer](https://github.com/SamVerschueren/listr-verbose-renderer). I don't want to add `momentjs` because I it's quite bloated in my opinion. So I think I will go with [`date-fns/format`](https://date-fns.org/docs/format). What do you think about something like this?

```js
const listr = new Listr([], {
    renderer: 'verbose',
    dateFormat: 'YYYY-MM-DD HH:mm:ss'
})
```

**Comment by SamVerschueren** [comment]
Added in `v0.11.0` (https://github.com/SamVerschueren/listr-verbose-renderer#options)

**Comment by parro-it** [comment]
@SamVerschueren  great, thank you!
